### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by sumachanabc** [sumachanabc/furima-39812#20]
自身のフリマアプリのURL
https://furima-39812.onrender.com/

Basic認証
ID:admin
パスワード:2222

出品者用のメールアドレスとパスワード
qqq@gmail.com
111qqq
購入者用のメールアドレスとパスワード
aaa@gmail.com
111qqq

**Comment by mo1015** [comment]
@sumachanabc さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **カテゴリーは、「---、メンズ、レディース、ベビー・キッズ、インテリア・住まい・小物、本・音楽・ゲーム、おもちゃ・ホビー・グッズ、家電・スマホ・カメラ、スポーツ・レジャー、ハンドメイド、その他」の11項目が表示されること（--- は初期値として設定すること）**
- [ ] **商品の状態は、「---、新品・未使用、未使用に近い、目立った傷や汚れなし、やや傷や汚れあり、傷や汚れあり、全体的に状態が悪い」の7項目が表示されること（--- は初期値として設定すること）**
- [ ] **配送料の負担は、「---、着払い(購入者負担)、送料込み(出品者負担)」の3項目が表示されること（--- は初期値として設定すること）**
- [ ] **発送元の地域は、「---」と47都道府県の合計48項目が表示されること（--- は初期値として設定すること）**
- [ ] **発送までの日数は、「---、1\~2日で発送、2\~3日で発送、4\~7日で発送」の4項目が表示されること（--- は初期値として設定すること）**
↓
現在、上記すべての入力欄に「選択してください」という項目が存在しています。要件にはない項目のため修正しましょう。

- [ ] **必要な情報を適切に入力して「購入」ボタンを押すと、商品の購入ができること**
必要な情報を適切に入力して「購入」ボタンを押しても、売却済みになりません。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by sumachanabc** [comment]
ご指摘ありがとうございます。修正しました。

**Comment by moom1122** [comment]
@sumachanabc さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、再度、修正をしていただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **必要な情報を適切に入力して「購入」ボタンを押すと、商品の購入ができること**
必要な情報を適切に入力して「購入」ボタンを押しても、売却済みになりません。


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by sumachanabc** [comment]
ご指摘ありがとうございます。確認しましたら、order.rbにorder_shipping_address.rbに移して消すはずのtokenのバリデーション等が残ったままのようでしたので購入時にダブルでバリデーションが行われ、保存が上手くいかなかったようです。
商品購入機能実装時はordersテーブルへの保存内容指定でtokenをしていて消すように指示されたため、コードレビュー前の自分での挙動確認では商品購入ができていたようです。
修正しましたのでご確認よろしくお願いいたします。

**Comment by shodai-ito** [comment]
@sumachanabc さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
